//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.20 at 05:56:46 AM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://local.soap.xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.soap.local;
