//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.09 at 09:39:46 PM WAT 
//


package xml.soap.station;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StationResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StationResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bonus" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Docks" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DocksDisp" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="localName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pais" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="municipio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="distrito" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="avenida" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="distancia" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StationResponseType", propOrder = {
    "id",
    "name",
    "bonus",
    "docks",
    "docksDisp",
    "localName",
    "pais",
    "provincia",
    "municipio",
    "distrito",
    "avenida",
    "latitude",
    "longitude",
    "distancia"
})
public class StationResponseType {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    protected int bonus;
    @XmlElement(name = "Docks")
    protected int docks;
    @XmlElement(name = "DocksDisp")
    protected int docksDisp;
    @XmlElement(required = true)
    protected String localName;
    @XmlElement(required = true)
    protected String pais;
    @XmlElement(required = true)
    protected String provincia;
    @XmlElement(required = true)
    protected String municipio;
    @XmlElement(required = true)
    protected String distrito;
    @XmlElement(required = true)
    protected String avenida;
    protected float latitude;
    protected float longitude;
    protected int distancia;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bonus property.
     * 
     */
    public int getBonus() {
        return bonus;
    }

    /**
     * Sets the value of the bonus property.
     * 
     */
    public void setBonus(int value) {
        this.bonus = value;
    }

    /**
     * Gets the value of the docks property.
     * 
     */
    public int getDocks() {
        return docks;
    }

    /**
     * Sets the value of the docks property.
     * 
     */
    public void setDocks(int value) {
        this.docks = value;
    }

    /**
     * Gets the value of the docksDisp property.
     * 
     */
    public int getDocksDisp() {
        return docksDisp;
    }

    /**
     * Sets the value of the docksDisp property.
     * 
     */
    public void setDocksDisp(int value) {
        this.docksDisp = value;
    }

    /**
     * Gets the value of the localName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalName() {
        return localName;
    }

    /**
     * Sets the value of the localName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalName(String value) {
        this.localName = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPais(String value) {
        this.pais = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvincia(String value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the municipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipio() {
        return municipio;
    }

    /**
     * Sets the value of the municipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipio(String value) {
        this.municipio = value;
    }

    /**
     * Gets the value of the distrito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrito() {
        return distrito;
    }

    /**
     * Sets the value of the distrito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrito(String value) {
        this.distrito = value;
    }

    /**
     * Gets the value of the avenida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvenida() {
        return avenida;
    }

    /**
     * Sets the value of the avenida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvenida(String value) {
        this.avenida = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public float getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(float value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public float getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(float value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the distancia property.
     * 
     */
    public int getDistancia() {
        return distancia;
    }

    /**
     * Sets the value of the distancia property.
     * 
     */
    public void setDistancia(int value) {
        this.distancia = value;
    }

}
