//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.14 at 05:31:25 PM WAT 
//


package xml.soap.anuncios;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://anuncios.soap.xml}HeaderType"/&gt;
 *         &lt;element name="Body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="dataexpiracao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="bloquear" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "AddAnuncioRequest")
public class AddAnuncioRequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Body", required = true)
    protected AddAnuncioRequest.Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link AddAnuncioRequest.Body }
     *     
     */
    public AddAnuncioRequest.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddAnuncioRequest.Body }
     *     
     */
    public void setBody(AddAnuncioRequest.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="dataexpiracao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="bloquear" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titulo",
        "local",
        "descricao",
        "dataexpiracao",
        "bloquear"
    })
    public static class Body {

        @XmlElement(required = true)
        protected String titulo;
        @XmlElement(required = true)
        protected String local;
        @XmlElement(required = true)
        protected String descricao;
        @XmlElement(required = true)
        protected String dataexpiracao;
        @XmlElement(required = true)
        protected String bloquear;

        /**
         * Gets the value of the titulo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitulo() {
            return titulo;
        }

        /**
         * Sets the value of the titulo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitulo(String value) {
            this.titulo = value;
        }

        /**
         * Gets the value of the local property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocal() {
            return local;
        }

        /**
         * Sets the value of the local property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocal(String value) {
            this.local = value;
        }

        /**
         * Gets the value of the descricao property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescricao() {
            return descricao;
        }

        /**
         * Sets the value of the descricao property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescricao(String value) {
            this.descricao = value;
        }

        /**
         * Gets the value of the dataexpiracao property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataexpiracao() {
            return dataexpiracao;
        }

        /**
         * Sets the value of the dataexpiracao property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataexpiracao(String value) {
            this.dataexpiracao = value;
        }

        /**
         * Gets the value of the bloquear property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBloquear() {
            return bloquear;
        }

        /**
         * Sets the value of the bloquear property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBloquear(String value) {
            this.bloquear = value;
        }

    }

}
