//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.11 at 10:05:13 PM WAT 
//


package xml.soap.anuncios;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
// <<<<<<< HEAD
 * <p>Classe Java de anonymous complex type.
 * 
 * <p>O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
=======
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
>>>>>>> olivio
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://anuncios.soap.xml}HeaderType"/&gt;
 *         &lt;element name="Body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="localId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "AllAnuncioRequest")
public class AllAnuncioRequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Body", required = true)
    protected AllAnuncioRequest.Body body;

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade header.
=======
     * Gets the value of the header property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade header.
=======
     * Sets the value of the header property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade body.
=======
     * Gets the value of the body property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link AllAnuncioRequest.Body }
     *     
     */
    public AllAnuncioRequest.Body getBody() {
        return body;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade body.
=======
     * Sets the value of the body property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link AllAnuncioRequest.Body }
     *     
     */
    public void setBody(AllAnuncioRequest.Body value) {
        this.body = value;
    }


    /**
// <<<<<<< HEAD
     * <p>Classe Java de anonymous complex type.
     * 
     * <p>O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
=======
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
>>>>>>> olivio
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="localId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userId",
        "localId",
        "latitude",
        "longitude"
    })
    public static class Body {

        protected long userId;
        protected long localId;
        protected double latitude;
        protected double longitude;

        /**
// <<<<<<< HEAD
         * Obtém o valor da propriedade userId.
=======
         * Gets the value of the userId property.
>>>>>>> olivio
         * 
         */
        public long getUserId() {
            return userId;
        }

        /**
// <<<<<<< HEAD
         * Define o valor da propriedade userId.
=======
         * Sets the value of the userId property.
>>>>>>> olivio
         * 
         */
        public void setUserId(long value) {
            this.userId = value;
        }

        /**
// <<<<<<< HEAD
         * Obtém o valor da propriedade localId.
=======
         * Gets the value of the localId property.
>>>>>>> olivio
         * 
         */
        public long getLocalId() {
            return localId;
        }

        /**
// <<<<<<< HEAD
         * Define o valor da propriedade localId.
=======
         * Sets the value of the localId property.
>>>>>>> olivio
         * 
         */
        public void setLocalId(long value) {
            this.localId = value;
        }

        /**
// <<<<<<< HEAD
         * Obtém o valor da propriedade latitude.
=======
         * Gets the value of the latitude property.
>>>>>>> olivio
         * 
         */
        public double getLatitude() {
            return latitude;
        }

        /**
// <<<<<<< HEAD
         * Define o valor da propriedade latitude.
=======
         * Sets the value of the latitude property.
>>>>>>> olivio
         * 
         */
        public void setLatitude(double value) {
            this.latitude = value;
        }

        /**
// <<<<<<< HEAD
         * Obtém o valor da propriedade longitude.
=======
         * Gets the value of the longitude property.
>>>>>>> olivio
         * 
         */
        public double getLongitude() {
            return longitude;
        }

        /**
// <<<<<<< HEAD
         * Define o valor da propriedade longitude.
=======
         * Sets the value of the longitude property.
>>>>>>> olivio
         * 
         */
        public void setLongitude(double value) {
            this.longitude = value;
        }

    }

}
