//
// <<<<<<< HEAD
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.11 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2025.06.11 às 01:13:46 PM WAT 
// =======
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.11 at 10:05:13 PM WAT 
// >>>>>>> olivio
//


package xml.soap.anuncios;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.anuncios package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.anuncios
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddAnuncioRequest }
     * 
     */
    public AddAnuncioRequest createAddAnuncioRequest() {
        return new AddAnuncioRequest();
    }

    /**
     * Create an instance of {@link AllAnuncioRequest }
     * 
     */
    public AllAnuncioRequest createAllAnuncioRequest() {
        return new AllAnuncioRequest();
    }

    /**
// <<<<<<< HEAD
     * Create an instance of {@link GetAnuncioRequest }
     * 
     */
    public GetAnuncioRequest createGetAnuncioRequest() {
        return new GetAnuncioRequest();
    }

    /**
=======
>>>>>>> olivio
     * Create an instance of {@link RemoveAnuncioRequest }
     * 
     */
    public RemoveAnuncioRequest createRemoveAnuncioRequest() {
        return new RemoveAnuncioRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link AddAnuncioRequest.Body }
     * 
     */
    public AddAnuncioRequest.Body createAddAnuncioRequestBody() {
        return new AddAnuncioRequest.Body();
    }

    /**
     * Create an instance of {@link AddAnuncioResponse }
     * 
     */
    public AddAnuncioResponse createAddAnuncioResponse() {
        return new AddAnuncioResponse();
    }

    /**
     * Create an instance of {@link PoliticaEntregaType }
     * 
     */
    public PoliticaEntregaType createPoliticaEntregaType() {
        return new PoliticaEntregaType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link LocalType }
     * 
     */
    public LocalType createLocalType() {
        return new LocalType();
    }

    /**
     * Create an instance of {@link AllAnuncioRequest.Body }
     * 
     */
    public AllAnuncioRequest.Body createAllAnuncioRequestBody() {
        return new AllAnuncioRequest.Body();
    }

    /**
     * Create an instance of {@link AllAnuncioResponse }
     * 
     */
    public AllAnuncioResponse createAllAnuncioResponse() {
        return new AllAnuncioResponse();
    }

    /**
     * Create an instance of {@link AnuncioType }
     * 
     */
    public AnuncioType createAnuncioType() {
        return new AnuncioType();
    }

    /**
// <<<<<<< HEAD
     * Create an instance of {@link GetAnuncioRequest.Body }
     * 
     */
    public GetAnuncioRequest.Body createGetAnuncioRequestBody() {
        return new GetAnuncioRequest.Body();
    }

    /**
     * Create an instance of {@link GetAnuncioResponse }
     * 
     */
    public GetAnuncioResponse createGetAnuncioResponse() {
        return new GetAnuncioResponse();
    }

    /**
=======
>>>>>>> olivio
     * Create an instance of {@link RemoveAnuncioRequest.Body }
     * 
     */
    public RemoveAnuncioRequest.Body createRemoveAnuncioRequestBody() {
        return new RemoveAnuncioRequest.Body();
    }

    /**
     * Create an instance of {@link RemoveAnuncioResponse }
     * 
     */
    public RemoveAnuncioResponse createRemoveAnuncioResponse() {
        return new RemoveAnuncioResponse();
    }

    /**
     * Create an instance of {@link CondicaoPerfilType }
     * 
     */
    public CondicaoPerfilType createCondicaoPerfilType() {
        return new CondicaoPerfilType();
    }

}
