//
// <<<<<<< HEAD
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.11 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2025.06.11 às 01:13:46 PM WAT 
// =======
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.11 at 10:05:13 PM WAT 
// >>>>>>> olivio
//


package xml.soap.anuncios;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
// <<<<<<< HEAD
 * <p>Classe Java de PoliticaTipo.
 * 
 * <p>O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
=======
 * <p>Java class for PoliticaTipo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
>>>>>>> olivio
 * <p>
 * <pre>
 * &lt;simpleType name="PoliticaTipo"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WHITELIST"/&gt;
 *     &lt;enumeration value="BLACKLIST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PoliticaTipo")
@XmlEnum
public enum PoliticaTipo {

    WHITELIST,
    BLACKLIST;

    public String value() {
        return name();
    }

    public static PoliticaTipo fromValue(String v) {
        return valueOf(v);
    }

}
