//
// <<<<<<< HEAD
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.11 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2025.06.11 às 01:13:46 PM WAT 
// =======
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.11 at 10:05:13 PM WAT 
// >>>>>>> olivio
//


package xml.soap.anuncios;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
// <<<<<<< HEAD
 * <p>Classe Java de anonymous complex type.
 * 
 * <p>O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
// =======
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
// >>>>>>> olivio
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mensagem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mensagem",
    "status",
    "id"
})
@XmlRootElement(name = "RemoveAnuncioResponse")
public class RemoveAnuncioResponse {

    @XmlElement(required = true)
    protected String mensagem;
    protected boolean status;
    protected int id;

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade mensagem.
=======
     * Gets the value of the mensagem property.
// >>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensagem() {
        return mensagem;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade mensagem.
=======
     * Sets the value of the mensagem property.
// >>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensagem(String value) {
        this.mensagem = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade status.
=======
     * Gets the value of the status property.
// >>>>>>> olivio
     * 
     */
    public boolean isStatus() {
        return status;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade status.
=======
     * Sets the value of the status property.
// >>>>>>> olivio
     * 
     */
    public void setStatus(boolean value) {
        this.status = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade id.
=======
     * Gets the value of the id property.
// >>>>>>> olivio
     * 
     */
    public int getId() {
        return id;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade id.
=======
     * Sets the value of the id property.
// >>>>>>> olivio
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
