//
// <<<<<<< HEAD
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.11 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2025.06.11 às 01:13:46 PM WAT 
// =======
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.11 at 10:05:13 PM WAT 
// >>>>>>> olivio
//


package xml.soap.anuncios;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
// <<<<<<< HEAD
 * <p>Classe Java de UserType complex type.
 * 
 * <p>O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
=======
 * <p>Java class for UserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
>>>>>>> olivio
 * 
 * <pre>
 * &lt;complexType name="UserType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="genero" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="profissao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="telefone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="foto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserType", propOrder = {
    "id",
    "email",
    "username",
    "genero",
    "profissao",
    "telefone",
    "foto",
    "token"
})
public class UserType {

    protected long id;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String genero;
    @XmlElement(required = true)
    protected String profissao;
    @XmlElement(required = true)
    protected String telefone;
    @XmlElement(required = true)
    protected String foto;
    @XmlElement(required = true)
    protected String token;

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade id.
=======
     * Gets the value of the id property.
>>>>>>> olivio
     * 
     */
    public long getId() {
        return id;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade id.
=======
     * Sets the value of the id property.
>>>>>>> olivio
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade email.
=======
     * Gets the value of the email property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade email.
=======
     * Sets the value of the email property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade username.
=======
     * Gets the value of the username property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade username.
=======
     * Sets the value of the username property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade genero.
=======
     * Gets the value of the genero property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenero() {
        return genero;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade genero.
=======
     * Sets the value of the genero property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenero(String value) {
        this.genero = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade profissao.
=======
     * Gets the value of the profissao property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfissao() {
        return profissao;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade profissao.
=======
     * Sets the value of the profissao property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfissao(String value) {
        this.profissao = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade telefone.
=======
     * Gets the value of the telefone property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefone() {
        return telefone;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade telefone.
=======
     * Sets the value of the telefone property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefone(String value) {
        this.telefone = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade foto.
=======
     * Gets the value of the foto property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoto() {
        return foto;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade foto.
=======
     * Sets the value of the foto property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoto(String value) {
        this.foto = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade token.
=======
     * Gets the value of the token property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade token.
=======
     * Sets the value of the token property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

}
