//
// <<<<<<< HEAD
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.11 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2025.06.11 às 01:13:46 PM WAT 
// =======
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.11 at 10:05:13 PM WAT 
// >>>>>>> olivio
//


package xml.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
// <<<<<<< HEAD
 * <p>Classe Java de anonymous complex type.
 * 
 * <p>O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
=======
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
>>>>>>> olivio
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="estado" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="mensagem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bonus" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="localName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="dockItem" type="{http://soap.xml}DockType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "estado",
    "mensagem",
    "id",
    "name",
    "bonus",
    "localName",
    "latitude",
    "longitude",
    "dockItem"
})
@XmlRootElement(name = "GetStationResponse")
public class GetStationResponse {

    protected boolean estado;
    @XmlElement(required = true)
    protected String mensagem;
    protected long id;
    @XmlElement(required = true)
    protected String name;
    protected int bonus;
    @XmlElement(required = true)
    protected String localName;
    protected float latitude;
    protected float longitude;
    @XmlElement(required = true)
    protected List<DockType> dockItem;

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade estado.
=======
     * Gets the value of the estado property.
>>>>>>> olivio
     * 
     */
    public boolean isEstado() {
        return estado;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade estado.
=======
     * Sets the value of the estado property.
>>>>>>> olivio
     * 
     */
    public void setEstado(boolean value) {
        this.estado = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade mensagem.
=======
     * Gets the value of the mensagem property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensagem() {
        return mensagem;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade mensagem.
=======
     * Sets the value of the mensagem property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensagem(String value) {
        this.mensagem = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade id.
=======
     * Gets the value of the id property.
>>>>>>> olivio
     * 
     */
    public long getId() {
        return id;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade id.
=======
     * Sets the value of the id property.
>>>>>>> olivio
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade name.
=======
     * Gets the value of the name property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade name.
=======
     * Sets the value of the name property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade bonus.
=======
     * Gets the value of the bonus property.
>>>>>>> olivio
     * 
     */
    public int getBonus() {
        return bonus;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade bonus.
=======
     * Sets the value of the bonus property.
>>>>>>> olivio
     * 
     */
    public void setBonus(int value) {
        this.bonus = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade localName.
=======
     * Gets the value of the localName property.
>>>>>>> olivio
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalName() {
        return localName;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade localName.
=======
     * Sets the value of the localName property.
>>>>>>> olivio
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalName(String value) {
        this.localName = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade latitude.
=======
     * Gets the value of the latitude property.
>>>>>>> olivio
     * 
     */
    public float getLatitude() {
        return latitude;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade latitude.
=======
     * Sets the value of the latitude property.
>>>>>>> olivio
     * 
     */
    public void setLatitude(float value) {
        this.latitude = value;
    }

    /**
// <<<<<<< HEAD
     * Obtém o valor da propriedade longitude.
=======
     * Gets the value of the longitude property.
>>>>>>> olivio
     * 
     */
    public float getLongitude() {
        return longitude;
    }

    /**
// <<<<<<< HEAD
     * Define o valor da propriedade longitude.
=======
     * Sets the value of the longitude property.
>>>>>>> olivio
     * 
     */
    public void setLongitude(float value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the dockItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dockItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDockItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DockType }
     * 
     * 
     */
    public List<DockType> getDockItem() {
        if (dockItem == null) {
            dockItem = new ArrayList<DockType>();
        }
        return this.dockItem;
    }

}
