//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.27 at 12:16:18 PM WAT 
//


package xml.replication;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.replication package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.replication
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReplicateRequest }
     * 
     */
    public ReplicateRequest createReplicateRequest() {
        return new ReplicateRequest();
    }

    /**
     * Create an instance of {@link ReplicateResponse }
     * 
     */
    public ReplicateResponse createReplicateResponse() {
        return new ReplicateResponse();
    }

    /**
     * Create an instance of {@link WriteReplicateRequest }
     * 
     */
    public WriteReplicateRequest createWriteReplicateRequest() {
        return new WriteReplicateRequest();
    }

    /**
     * Create an instance of {@link WriteReplicateResponse }
     * 
     */
    public WriteReplicateResponse createWriteReplicateResponse() {
        return new WriteReplicateResponse();
    }

}
