//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.11 at 10:05:13 PM WAT 
//


package xml.soap.user;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://user.soap.xml}HeaderType"/&gt;
 *         &lt;element name="Body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="datanascimento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="genero" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="telefone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "AddUserRequest")
public class AddUserRequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Body", required = true)
    protected AddUserRequest.Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link AddUserRequest.Body }
     *     
     */
    public AddUserRequest.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddUserRequest.Body }
     *     
     */
    public void setBody(AddUserRequest.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="datanascimento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="genero" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="telefone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "email",
        "password",
        "username",
        "datanascimento",
        "genero",
        "tipo",
        "telefone"
    })
    public static class Body {

        @XmlElement(required = true)
        protected String email;
        @XmlElement(required = true)
        protected String password;
        @XmlElement(required = true)
        protected String username;
        @XmlElement(required = true)
        protected String datanascimento;
        @XmlElement(required = true)
        protected String genero;
        protected int tipo;
        @XmlElement(required = true)
        protected String telefone;

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }

        /**
         * Gets the value of the username property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsername(String value) {
            this.username = value;
        }

        /**
         * Gets the value of the datanascimento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatanascimento() {
            return datanascimento;
        }

        /**
         * Sets the value of the datanascimento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatanascimento(String value) {
            this.datanascimento = value;
        }

        /**
         * Gets the value of the genero property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGenero() {
            return genero;
        }

        /**
         * Sets the value of the genero property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGenero(String value) {
            this.genero = value;
        }

        /**
         * Gets the value of the tipo property.
         * 
         */
        public int getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         */
        public void setTipo(int value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the telefone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefone() {
            return telefone;
        }

        /**
         * Sets the value of the telefone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefone(String value) {
            this.telefone = value;
        }

    }

}
