//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.09 at 09:39:46 PM WAT 
//


package xml.soap.user;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://user.soap.xml}HeaderType"/&gt;
 *         &lt;element name="Body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="chaveAntiga" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="novaChaver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="novoValor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "EditUserProfileRequest")
public class EditUserProfileRequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Body", required = true)
    protected EditUserProfileRequest.Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link EditUserProfileRequest.Body }
     *     
     */
    public EditUserProfileRequest.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditUserProfileRequest.Body }
     *     
     */
    public void setBody(EditUserProfileRequest.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="chaveAntiga" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="novaChaver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="novoValor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userId",
        "chaveAntiga",
        "novaChaver",
        "novoValor"
    })
    public static class Body {

        protected long userId;
        @XmlElement(required = true)
        protected String chaveAntiga;
        @XmlElement(required = true)
        protected String novaChaver;
        @XmlElement(required = true)
        protected String novoValor;

        /**
         * Gets the value of the userId property.
         * 
         */
        public long getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         */
        public void setUserId(long value) {
            this.userId = value;
        }

        /**
         * Gets the value of the chaveAntiga property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChaveAntiga() {
            return chaveAntiga;
        }

        /**
         * Sets the value of the chaveAntiga property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChaveAntiga(String value) {
            this.chaveAntiga = value;
        }

        /**
         * Gets the value of the novaChaver property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNovaChaver() {
            return novaChaver;
        }

        /**
         * Sets the value of the novaChaver property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNovaChaver(String value) {
            this.novaChaver = value;
        }

        /**
         * Gets the value of the novoValor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNovoValor() {
            return novoValor;
        }

        /**
         * Sets the value of the novoValor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNovoValor(String value) {
            this.novoValor = value;
        }

    }

}
