//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.20 at 05:56:46 AM WAT 
//


package xml.soap.user;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddUserRequest }
     * 
     */
    public AddUserRequest createAddUserRequest() {
        return new AddUserRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetCiclistaRequest }
     * 
     */
    public GetCiclistaRequest createGetCiclistaRequest() {
        return new GetCiclistaRequest();
    }

    /**
     * Create an instance of {@link DeleteCiclistaRequest }
     * 
     */
    public DeleteCiclistaRequest createDeleteCiclistaRequest() {
        return new DeleteCiclistaRequest();
    }

    /**
     * Create an instance of {@link UpdateCiclistaRequest }
     * 
     */
    public UpdateCiclistaRequest createUpdateCiclistaRequest() {
        return new UpdateCiclistaRequest();
    }

    /**
     * Create an instance of {@link GetSaldoRequest }
     * 
     */
    public GetSaldoRequest createGetSaldoRequest() {
        return new GetSaldoRequest();
    }

    /**
     * Create an instance of {@link TransferPointsRequest }
     * 
     */
    public TransferPointsRequest createTransferPointsRequest() {
        return new TransferPointsRequest();
    }

    /**
     * Create an instance of {@link HistoricTrajectRequest }
     * 
     */
    public HistoricTrajectRequest createHistoricTrajectRequest() {
        return new HistoricTrajectRequest();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link ValidateTokenRequest }
     * 
     */
    public ValidateTokenRequest createValidateTokenRequest() {
        return new ValidateTokenRequest();
    }

    /**
     * Create an instance of {@link ValidateTokenResponse }
     * 
     */
    public ValidateTokenResponse createValidateTokenResponse() {
        return new ValidateTokenResponse();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link AddUserRequest.Body }
     * 
     */
    public AddUserRequest.Body createAddUserRequestBody() {
        return new AddUserRequest.Body();
    }

    /**
     * Create an instance of {@link LoginResponse.User }
     * 
     */
    public LoginResponse.User createLoginResponseUser() {
        return new LoginResponse.User();
    }

    /**
     * Create an instance of {@link GetUserRequest.Body }
     * 
     */
    public GetUserRequest.Body createGetUserRequestBody() {
        return new GetUserRequest.Body();
    }

    /**
     * Create an instance of {@link UserResponse }
     * 
     */
    public UserResponse createUserResponse() {
        return new UserResponse();
    }

    /**
     * Create an instance of {@link AllUsersRequest }
     * 
     */
    public AllUsersRequest createAllUsersRequest() {
        return new AllUsersRequest();
    }

    /**
     * Create an instance of {@link UserListResponse }
     * 
     */
    public UserListResponse createUserListResponse() {
        return new UserListResponse();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link LoginCiclistaRequest }
     * 
     */
    public LoginCiclistaRequest createLoginCiclistaRequest() {
        return new LoginCiclistaRequest();
    }

    /**
     * Create an instance of {@link AddCiclistaRequest }
     * 
     */
    public AddCiclistaRequest createAddCiclistaRequest() {
        return new AddCiclistaRequest();
    }

    /**
     * Create an instance of {@link GetCiclistaRequest.Body }
     * 
     */
    public GetCiclistaRequest.Body createGetCiclistaRequestBody() {
        return new GetCiclistaRequest.Body();
    }

    /**
     * Create an instance of {@link DeleteCiclistaRequest.Body }
     * 
     */
    public DeleteCiclistaRequest.Body createDeleteCiclistaRequestBody() {
        return new DeleteCiclistaRequest.Body();
    }

    /**
     * Create an instance of {@link UpdateCiclistaRequest.Body }
     * 
     */
    public UpdateCiclistaRequest.Body createUpdateCiclistaRequestBody() {
        return new UpdateCiclistaRequest.Body();
    }

    /**
     * Create an instance of {@link GetSaldoRequest.Body }
     * 
     */
    public GetSaldoRequest.Body createGetSaldoRequestBody() {
        return new GetSaldoRequest.Body();
    }

    /**
     * Create an instance of {@link GetSaldoResponse }
     * 
     */
    public GetSaldoResponse createGetSaldoResponse() {
        return new GetSaldoResponse();
    }

    /**
     * Create an instance of {@link TransferPointsRequest.Body }
     * 
     */
    public TransferPointsRequest.Body createTransferPointsRequestBody() {
        return new TransferPointsRequest.Body();
    }

    /**
     * Create an instance of {@link TransferPointsResponse }
     * 
     */
    public TransferPointsResponse createTransferPointsResponse() {
        return new TransferPointsResponse();
    }

    /**
     * Create an instance of {@link HistoricTrajectRequest.Body }
     * 
     */
    public HistoricTrajectRequest.Body createHistoricTrajectRequestBody() {
        return new HistoricTrajectRequest.Body();
    }

    /**
     * Create an instance of {@link HistoricTrajectResponse }
     * 
     */
    public HistoricTrajectResponse createHistoricTrajectResponse() {
        return new HistoricTrajectResponse();
    }

    /**
     * Create an instance of {@link TrajectType }
     * 
     */
    public TrajectType createTrajectType() {
        return new TrajectType();
    }

    /**
     * Create an instance of {@link PartidaType }
     * 
     */
    public PartidaType createPartidaType() {
        return new PartidaType();
    }

    /**
     * Create an instance of {@link ChegadaType }
     * 
     */
    public ChegadaType createChegadaType() {
        return new ChegadaType();
    }

}
