//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.27 at 12:16:18 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://user.soap.xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.soap.user;
