//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.14 at 05:31:25 PM WAT 
//


package xml.soap.user;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrajectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrajectType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="partida" type="{http://user.soap.xml}PartidaType"/&gt;
 *         &lt;element name="chegada" type="{http://user.soap.xml}ChegadaType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrajectType", propOrder = {
    "partida",
    "chegada"
})
public class TrajectType {

    @XmlElement(required = true)
    protected PartidaType partida;
    @XmlElement(required = true)
    protected ChegadaType chegada;

    /**
     * Gets the value of the partida property.
     * 
     * @return
     *     possible object is
     *     {@link PartidaType }
     *     
     */
    public PartidaType getPartida() {
        return partida;
    }

    /**
     * Sets the value of the partida property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartidaType }
     *     
     */
    public void setPartida(PartidaType value) {
        this.partida = value;
    }

    /**
     * Gets the value of the chegada property.
     * 
     * @return
     *     possible object is
     *     {@link ChegadaType }
     *     
     */
    public ChegadaType getChegada() {
        return chegada;
    }

    /**
     * Sets the value of the chegada property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChegadaType }
     *     
     */
    public void setChegada(ChegadaType value) {
        this.chegada = value;
    }

}
